### ISSUE TITLE
Merchant ID missing on Data Model

### ISSUE THREAD

**Issue by sblabreu** [opasch/fidelity#10]
current data model is missing the merchant ID

  "cart_id": "9roj8f70TUEU",
  "client_address": "0xab96032f5a7Efe3F95622c5B9D98D50F96a91756",
  "total_items": 3,
  "total_price": "15.00",
  "items": [

suggestion

  "cart_id": "9roj8f70TUEU",
  "merchant_id": "xxxxxxxxxxxxxxxxxx",
  "client_address": "0xab96032f5a7Efe3F95622c5B9D98D50F96a91756",
  "total_items": 3,
  "total_price": "15.00",
  "items": [

Note that merchant_id is an example

**Comment by jambtc** [comment]
i solved this in #15
