### ISSUE TITLE
rule engine rest/api connectivity

### ISSUE THREAD

**Issue by opasch** [opasch/fidelity#13]
As a solution architect,
I want to create a connection between the rule engine and the backend of the fidelity application.
This interface has to allow:

the backend application must be able to connect with the rule engine via the use of REST API and transfer all the needed information.
Generally speaking this information should be the cart content and the amount paid in euro.

**Comment by sblabreu** [comment]
REST interface proposal sent by mail

**Comment by sblabreu** [comment]
Rest api implement with openapi documentation.
