### ISSUE TITLE
[Rule Engine] Ambiguous answer when using random merchant_id

### ISSUE THREAD

**Issue by sblabreu** [opasch/fidelity#16]
I noticed that if I use a merchant id different from 1234 the server responds "No Valid Schema Detected or payload not according to defined schema". Maybe could be better "No merchant id found" or similar. That answer is ambiguous.

**Comment by jambtc** [comment]
Exact! I am not able to understand if I am wrong to send the payload format or it is only the merchant id that is incorrect.

**Comment by jambtc** [comment]
by the way, if I send a payload with merchant_id=1234 I receive this response "Event not valid, check header combination for merchant_id Parameter" ...

**Comment by sblabreu** [comment]
Hi,

Apologies as it seems the docker image was not loading the latest " latest"
I now include the version on the endpoint http://164.68.126.56:5000/health

So I now send the following event I have some rule triggered

curl -X POST "http://164.68.126.56:5000/api/v1/event" -H "accept:
application/json" -H "x-fre-origin: 1234" -H "Authorization: *<API Key>*"
-H "content-type: application/json" -d "{ \"event\":
{\"id\":\"fidelity:NIHlnz5Ftb\",\"redirect_url\":\"http:\\/\\/localhost\\/fidelize-dashboard\\/index.php?r=ipn\\/rules\",\"merchant_id\":\"1234\",\"customer_id\":\"2\",\"order_number\":\"51612\",\"order_total\":\"99\",\"items\":[{\"product_id\":\"5\",\"product_name\":\"iPod
Nano\",\"product_price\":\"99\"}],\"total_items\":\"1\",\"total_price\":\"15\",\"nonce\":\"1608810363358342\",\"client_address\":\"0xda9e2a20a018717d073a7acdfe93a099453b6844\",\"cart_id\":\"NIHlnz5Ftb\"}}"
{"event":{"group":{"total_items":["ok"]}}}

the "total_items" rule is triggering the proxy_backend action but the POST
to the backend results into an error response. Did something hit the server?

BR,
SA
